#!/usr/bin/env python3
"""Unit tests for the agentic PoC validation layer.

Run:  python3 -m pytest tools/agentic/tests/ -q
"""

import json
import os
import subprocess
import sys
import unittest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

FIXTURES = os.path.join(os.path.dirname(__file__), "fixtures")
APP_VULN = os.path.join(FIXTURES, "app_vuln")
APP_FIXED = os.path.join(FIXTURES, "app_fixed")

from noise_filter import (  # noqa: E402
    classify_finding,
    triage,
    CLASS_FAMILIES,
    SOURCE_TOKENS,
    SANITIZER_TOKENS,
    IGNORE_PATH_RE,
)
from poc_validator import (  # noqa: E402
    _family,
    class_default_payloads,
    build_harness,
    CLASS_MARKERS,
)
from sandbox_runner import detect_backend, run_in_sandbox  # noqa: E402
from agentic_audit import (  # noqa: E402
    _class_from_check,
    _list_candidate_files,
    _fill_snippets,
)


class TestNoiseFilter(unittest.TestCase):
    def test_r1_path_ignore(self):
        self.assertTrue(IGNORE_PATH_RE.search("src/tests/foo.py"))
        self.assertTrue(IGNORE_PATH_RE.search("node_modules/x/index.js"))
        self.assertFalse(IGNORE_PATH_RE.search("src/app.py"))

    def test_r2_generated(self):
        f = classify_finding(
            {"path": "src/x.py", "line": 1, "severity": "ERROR",
             "code": "// auto-generated by protoc-gen-x"}, None)
        self.assertEqual(f["decision"], "IGNORE")

    def test_r3_severity_floor(self):
        f = classify_finding(
            {"path": "src/x.py", "line": 1, "severity": "INFO", "code": "x"})
        self.assertEqual(f["decision"], "STATIC_ONLY")

    def test_r4_snake_case_source_token(self):
        # underscores previously broke \b word-boundary matching
        self.assertTrue(SOURCE_TOKENS.search("open(user_input)"))
        self.assertTrue(SOURCE_TOKENS.search("subprocess.run(req_data, shell=True)"))
        self.assertFalse(SOURCE_TOKENS.search("echo output"))

    def test_r5_sanitizer_hint(self):
        self.assertTrue(SANITIZER_TOKENS.search("return html.escape(x)"))
        self.assertTrue(SANITIZER_TOKENS.search("shlex.quote(x)"))

    def test_r6_family_dedupe(self):
        raw = [
            {"path": "app.py", "line": 26, "severity": "ERROR",
             "vuln_class": "command_injection", "code": "subprocess.run(x, shell=True)"},
            {"path": "app.py", "line": 26, "severity": "ERROR",
             "vuln_class": "subprocess_shell_true", "code": "subprocess.run(x, shell=True)"},
            {"path": "app.py", "line": 33, "severity": "ERROR",
             "vuln_class": "path_traversal", "code": "open(user_input)"},
        ]
        t = triage(raw)
        self.assertEqual(len(t["poc_candidates"]), 2)  # cmd dup merged, traversal kept

    def test_family_map(self):
        self.assertEqual(CLASS_FAMILIES["subprocess_shell_true"], "command_exec")
        self.assertEqual(_family("subprocess_shell_true"), "command_exec")
        self.assertEqual(_family("unknown_class"), "unknown_class")


class TestHarness(unittest.TestCase):
    def _lines(self, rel):
        return os.path.join(APP_VULN, rel)

    def test_line_to_function_mapping(self):
        # fixture: run_cmd_safe ~18-21, run_cmd ~24-27, run_cmd_popen ~30-33,
        # read_note ~35-39 — each sink must map to its own function
        src = open(self._lines("vulnapp.py")).read()
        for line, expect in ((20, "run_cmd_safe"), (26, "run_cmd"),
                             (32, "run_cmd_popen"), (37, "read_note")):
            h, desc = build_harness(
                {"path": "vulnapp.py", "line": line}, APP_VULN, "x")
            self.assertIsNotNone(h, desc)
            self.assertIn(expect, desc, f"line {line} mapped wrong")

    def test_function_hint_anchoring(self):
        h, desc = build_harness(
            {"path": "vulnapp.py", "line": 9999}, APP_FIXED, "x",
            function_hint="read_note")
        self.assertIsNotNone(h, desc)
        self.assertIn("read_note", desc)

    def test_function_hint_missing(self):
        h, desc = build_harness(
            {"path": "vulnapp.py", "line": 1}, APP_FIXED, "x",
            function_hint="nope_fn")
        self.assertIsNone(h)
        self.assertIn("not found", desc)


class TestPayloads(unittest.TestCase):
    def test_depth_ladder(self):
        ps = class_default_payloads("file_read")
        self.assertIn("../../../../../../../../etc/passwd", ps)

    def test_marker_tokens(self):
        self.assertEqual(CLASS_MARKERS["command_exec"][0], "PWN_MARKER")
        self.assertIn("root:x:0", CLASS_MARKERS["file_read"][0])


class TestSandbox(unittest.TestCase):
    def test_detect_backend(self):
        info = detect_backend("jail")
        self.assertEqual(info["backend"], "jail")
        self.assertTrue(info["available"])

    def test_run_in_sandbox(self):
        r = run_in_sandbox([sys.executable, "-c", "print('OK')"], timeout=15,
                           backend="jail")
        self.assertEqual(r["exit"], 0)
        self.assertIn("OK", r["stdout"])

    def test_network_blocked(self):
        r = run_in_sandbox(
            [sys.executable, "-c",
             "import socket; s=socket.socket(); print('NOPE')"],
            timeout=15, backend="jail")
        self.assertNotEqual(r["exit"], 0)
        self.assertNotIn("NOPE", r["stdout"])


class TestAgenticAuditUnits(unittest.TestCase):
    def test_class_from_check(self):
        # subprocess-shell-true is family-mapped (command_exec) downstream
        self.assertEqual(_class_from_check("python.lang.security.audit.subprocess-shell-true", {}),
                         "subprocess_shell_true")
        self.assertEqual(_class_from_check("foo.command-injection", {}), "command_injection")
        self.assertEqual(_class_from_check("foo.path-traversal", {}), "path_traversal")
        self.assertEqual(_class_from_check("xss.evil", {"cwe": ["CWE-79"]}), "xss")

    def test_list_candidate_files(self):
        files = _list_candidate_files(APP_VULN)
        self.assertTrue(any(f.endswith("vulnapp.py") for f in files))
        self.assertTrue(all(f.endswith(tuple(".py .js .go".split())) for f in files))

    def test_fill_snippets(self):
        lines = {"vulnapp.py": ["a", "b", "subprocess.run(x, shell=True)"]}
        raw = [{"path": "vulnapp.py", "line": 3, "code": ""}]
        _fill_snippets(raw, lines)
        self.assertIn("subprocess.run", raw[0]["code"])


class TestEndToEnd(unittest.TestCase):
    """Slow-ish integration: full audit + retest against the fixtures."""

    def test_audit_vulnerable(self):
        from agentic_audit import audit
        res = audit(APP_VULN, sandbox="jail")
        c = res["counts"]
        self.assertEqual(c["confirmed"], 3, res["validated"])
        self.assertEqual(c["blocked"], 1)
        verdicts = {(v["function"], v["validation"]["verdict"])
                    for v in res["validated"]}
        self.assertIn(("run_cmd", "CONFIRMED"), verdicts)
        self.assertIn(("run_cmd_popen", "CONFIRMED"), verdicts)
        self.assertIn(("read_note", "CONFIRMED"), verdicts)
        self.assertIn(("run_cmd_safe", "BLOCKED"), verdicts)

    def test_retest_fixed(self):
        from agentic_audit import audit, retest
        from pathlib import Path
        res = audit(APP_VULN, sandbox="jail")
        report = Path(res["report_dir"]) / "findings.json"
        rt = retest(report, APP_FIXED, "jail")
        self.assertEqual(rt["counts"]["FIXED"], 3, rt["results"])
        self.assertEqual(rt["counts"]["STILL_PRESENT"], 0)


if __name__ == "__main__":
    unittest.main()
