#!/usr/bin/env python3
"""
noise_filter.py — deterministic triage for SAST candidates.

Classifies each raw finding as:
  POC_CANDIDATE  → send to sandbox PoC validator
  STATIC_ONLY    → keep in appendix (low/info severity or non-executable)
  IGNORE         → test/vendor/generated code (unless explicitly kept)
  HUMAN_REVIEW   → looks interesting but reachability unclear

Rules (all deterministic, auditable via the `reasons` list):
  R1 path_ignore   : test/vendor/mock/fixture/build paths
  R2 generated     : generated-code markers in snippet
  R3 severity_floor: INFO/LOW-severity findings -> STATIC_ONLY
  R4 reachability  : sink line block references untrusted-input tokens
                     (request/params/argv/environ/cookie/header/...); absent → HUMAN_REVIEW
  R5 sanitizer     : sanitizer tokens near sink → flagged `sanitizer_hint` (auditor
                     must disprove before it can be CONFIRMED)
  R6 dedupe        : same vuln_class + file + sink within N lines → merge

Usage:
  python noise_filter.py --json '<findings-json-array>'
  python noise_filter.py --file findings.json
"""

from __future__ import annotations

import json
import re
import sys

# ── R1: paths we never send to the auditor ──────────────────────────────────
IGNORE_PATH_RE = re.compile(
    r"(^|/)(test|tests|__tests__|spec|specs|mocks?|fixtures?|vendor|node_modules|"
    r"dist|build|coverage|third_party|external|generated|gen/)"
    r"|\.(test|spec)\.(py|js|ts|jsx|tsx|go|rb|java|c|cpp|php)$",
    re.I,
)

# ── R2: generated code markers ──────────────────────────────────────────────
GENERATED_MARKERS = re.compile(
    r"(code generated by|autogenerated|auto-generated|do not edit|generated file|"
    r"@generated|swagger codegen|protoc-gen|___generated)",
    re.I,
)

# ── R4: untrusted input tokens (sink reachability heuristic) ─────────────────
# Negative lookbehind excludes letters/digits but ALLOWS '_' so snake_case
# identifiers like `user_input`, `req_data`, `url_path` match their token.
SOURCE_TOKENS = re.compile(
    r"(?<![A-Za-z0-9])(request|params?|query|body|input\w*|data\w*|form|json|"
    r"payload\w*|files?|upload\w*|argv|environ|os\.environ|getenv|stdin|"
    r"cookie\w*|headers?|session|search|term\w*|keyword\w*|username|password|"
    r"token\w*|url|uri|path\w*|id\w*)\b",
    re.I,
)

# ── R5: sanitizer tokens ─────────────────────────────────────────────────────
SANITIZER_TOKENS = re.compile(
    r"\b(escape|escaped|sanitize|sanitize|sanitiz|validate|validator|html\.escape|"
    r"markupsafe|safe_str|quote|quoted|urlencode|url_encode|prepared|placeholder|"
    r"parameterized|bind_param|escape_string|mysql_real_escape|pg_escape|"
    r"ent_quotes|strip_tags|striptags|filter_var|purify|dompurify|xss|"
    r"shell_quote|shlex|subprocess\.run\(.+shell=False|check_output\(.+shell=False)\b",
    re.I,
)

LOW_SEVERITIES = {"low", "info", "informational", "note", "none"}

DEFAULT_WINDOW = 5  # R6 dedupe window (lines)

# R6: findings that describe the SAME sink from different checkers are merged
# by vulnerability FAMILY (e.g. semgrep's subprocess-shell-true and our local
# command-injection rule both = command_exec; only one candidate is audited).
CLASS_FAMILIES = {
    "command_injection": "command_exec",
    "subprocess_shell_true": "command_exec",
    "subprocess_shell_false": "command_exec",
    "os_command": "command_exec",
    "command": "command_exec",
    "path_traversal": "file_read",
    "lfi": "file_read",
    "local_file_include": "file_read",
    "zip_slip": "file_read",
    "ssrf": "network",
    "open_redirect": "network",
    "xss": "xss",
    "sqli": "sqli",
    "ssti": "ssti",
    "secret_leak": "secret_leak",
}


def _snippet_context(lines: list[str], line_num: int, window: int = 12) -> str:
    """Grab a +/-window slice around the sink line for heuristic checks."""
    if not lines:
        return ""
    start = max(0, line_num - 1 - window)
    end = min(len(lines), line_num - 1 + window + 1)
    return "\n".join(lines[start:end])


def classify_finding(finding: dict, lines: list[str] | None = None, window: int = 12) -> dict:
    """Classify a single raw finding dict (mutates a copy). Returns decision."""
    f = dict(finding)
    fpath = (f.get("path") or f.get("file") or "").replace("\\", "/")
    line_num = int(f.get("line") or f.get("start", {}).get("line") or 0)
    severity = str(f.get("severity") or f.get("extra", {}).get("severity") or "medium").lower()
    vuln_class = f.get("vuln_class") or f.get("class") or f.get("check_id") or "unknown"
    f["vuln_class"] = vuln_class
    reasons: list[str] = []
    code = f.get("code") or f.get("snippet") or ""
    if not code and lines:
        code = _snippet_context(lines, line_num, window)

    # R1/R2
    if IGNORE_PATH_RE.search(fpath):
        return {**f, "decision": "IGNORE", "reasons": [f"R1 path_ignore: {fpath}"]}
    if GENERATED_MARKERS.search(code[:400]):
        return {**f, "decision": "IGNORE", "reasons": ["R2 generated-code marker in snippet"]}

    # R3 severity floor
    if severity in LOW_SEVERITIES:
        return {**f, "decision": "STATIC_ONLY", "reasons": [f"R3 severity floor ({severity})"]}

    # R4 reachability heuristic
    if code and SOURCE_TOKENS.search(code):
        reasons.append("R4 sink block references untrusted-input token")
    else:
        reasons.append("R4 no untrusted-input token near sink -> contextual review")

    # R5 sanitizer hint
    sanitized = bool(code and SANITIZER_TOKENS.search(code))
    if sanitized:
        reasons.append("R5 sanitizer token near sink (auditor must disprove)")
    f["sanitizer_hint"] = sanitized

    # Decision:
    #  - sanitizer hint present -> still POC_CANDIDATE (auditor must DISPROVE it:
    #    differential test decides BLOCKED vs CONFIRMED)
    #  - no source token near sink and no sanitizer -> HUMAN_REVIEW (contextual)
    no_source_token = "R4 no untrusted-input token" in reasons
    if not sanitized and no_source_token:
        decision = "HUMAN_REVIEW"
    else:
        decision = "POC_CANDIDATE"
    f["decision"] = decision
    f["reasons"] = reasons
    f["code"] = code
    f["line"] = line_num
    return f


def triage(findings: list[dict], repo_lines: dict[str, list[str]] | None = None) -> dict:
    """Run the full triage pass over raw findings.

    repo_lines: {path: [..lines..]} for snippet extraction (optional).
    Returns {'poc_candidates': [...], 'static_only': [...], 'ignored': [...],
             'human_review': [...], 'counts': {...}} plus dedupe applied.
    """
    buckets = {d: [] for d in ("POC_CANDIDATE", "STATIC_ONLY", "IGNORE", "HUMAN_REVIEW")}
    seen: set[tuple] = set()

    for raw in findings:
        lines = None
        if repo_lines:
            path = (raw.get("path") or raw.get("file") or "").replace("\\", "/")
            lines = repo_lines.get(path)
        f = classify_finding(raw, lines)

        # R6 dedupe (family-aware: subprocess-shell-true == command-injection)
        family = CLASS_FAMILIES.get(f.get("vuln_class"), f.get("vuln_class"))
        f["family"] = family
        key = (family, f.get("path"), f.get("line") // DEFAULT_WINDOW)
        if key in seen:
            continue
        seen.add(key)

        buckets[f["decision"]].append(f)

    return {
        "poc_candidates": buckets["POC_CANDIDATE"],
        "static_only": buckets["STATIC_ONLY"],
        "ignored": buckets["IGNORE"],
        "human_review": buckets["HUMAN_REVIEW"],
        "counts": {k: len(v) for k, v in buckets.items()},
    }


if __name__ == "__main__":
    import pathlib

    raw: list[dict] = []
    if len(sys.argv) > 1 and sys.argv[1] == "--file":
        raw = json.loads(pathlib.Path(sys.argv[2]).read_text())
    elif len(sys.argv) > 1 and sys.argv[1] == "--json":
        raw = json.loads(sys.argv[2])
    else:
        print(__doc__)
        sys.exit(1)
    print(json.dumps(triage(raw), indent=2))