#!/usr/bin/env bash
# scope_aggregator.sh — merge scope from multiple sources into scope.yaml.
# Usage:
#   scope_aggregator.sh --program <handle> --platform hackerone
#   scope_aggregator.sh --files scope-a.txt scope-b.txt --out config/scope.yaml
#   scope_aggregator.sh --securitytxt target.com
#
# Merges + dedupes + writes ~/.config/vulnera-mcp/scope.yaml (runtime scope).
set -uo pipefail

OUT_FILE="$HOME/.config/vulnera-mcp/scope.yaml"
mkdir -p "$(dirname "$OUT_FILE")"

TMP_IN=$(mktemp); TMP_OUT=$(mktemp)
: > "$TMP_IN"

while [ $# -gt 0 ]; do
  case "$1" in
    --program) PROGRAM="$2"; PLATFORM="${3:-hackerone}"; shift 3;;
    --files)
      shift
      while [ $# -gt 0 ] && [ "${1:0:1}" != "-" ]; do cat "$1" >> "$TMP_IN"; shift; done
      ;;
    --securitytxt)
      curl -s -m 15 "https://$2/.well-known/security.txt" 2>/dev/null >> "$TMP_IN"
      echo "" >> "$TMP_IN"
      shift 2;;
    --out) OUT_FILE="$2"; shift 2;;
    *) echo "unknown arg: $1" >&2; exit 2;;
  esac
done

# Fetch scope from platform if --program given
if [ -n "${PROGRAM:-}" ]; then
  echo "[*] fetching scope: $PROGRAM ($PLATFORM)"
  if [ "$PLATFORM" = "hackerone" ]; then
    # HackerOne policy page HTML — grab domains from JSON-LD / scope section
    curl -s -m 20 "https://hackerone.com/$PROGRAM/policy_scopes" 2>/dev/null \
      | grep -oE "https?://[a-zA-Z0-9.*_-]+" | sed 's|https\?://||' | sort -u >> "$TMP_IN"
  elif [ "$PLATFORM" = "bugcrowd" ]; then
    curl -s -m 20 "https://bugcrowd.com/$PROGRAM" 2>/dev/null \
      | grep -oE "[a-zA-Z0-9.*-]+\.[a-zA-Z]{2,}" | sort -u >> "$TMP_IN"
  fi
fi

[ -s "$TMP_IN" ] || { echo "[-] no scope data collected" >&2; exit 2; }

# Normalize + classify wildcards vs exact
python3 - "$TMP_IN" "$TMP_OUT" <<'PY'
import re, sys
from pathlib import Path
raw = set()
for line in Path(sys.argv[1]).read_text(errors='ignore').splitlines():
    line = line.strip().lower()
    if not line or line.startswith('#'): continue
    line = line.rstrip('/')
    line = re.sub(r'^https?://', '', line)
    line = re.sub(r'^www\.', '', line)
    if re.match(r'^(\*\.)?[a-z0-9*._-]+\.[a-z]{2,}$', line) and ' ' not in line:
        raw.add(line)
ins = sorted(x for x in raw if x.startswith('*') or '.' in x and not x.startswith('*'))
outs = sorted(x for x in raw if x.startswith('!'))
ins = sorted(x.lstrip('!') for x in raw if not x.startswith('!'))
with open(sys.argv[2], 'w') as f:
    f.write("# aggregated scope (generated by scope_aggregator.sh)\n")
    f.write("in_scope:\n")
    for e in ins: f.write(f'  - "{e}"\n')
    f.write("out_of_scope:\n")
    for e in outs: f.write(f'  - "{e}"\n')
    f.write("  - \"*.*\"   # fail-closed default\n")
PY

if [ -s "$TMP_OUT" ]; then
  cp "$TMP_OUT" "$OUT_FILE"
  echo "[+] aggregated scope written to $OUT_FILE"
  SCOPE_CHECKER="$(cd "$(dirname "$0")" && pwd)/scope_checker.py"
  python3 "$SCOPE_CHECKER" --list
  rm -f "$TMP_IN" "$TMP_OUT"
  exit 0
else
  echo "[-] aggregation failed" >&2
  rm -f "$TMP_IN" "$TMP_OUT"
  exit 1
fi